# Generated by Django 4.0.1 on 2022-04-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_districts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Districts',
        ),
    ]
