# Generated by Django 4.0.1 on 2022-04-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_delete_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_code',
            field=models.CharField( max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
